version: '3.9'
services:
  web:
    build: .
    container_name: cyclique_web
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: cyclique_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
